name: Katello
baseurl:
markdown: KramdownPygments
highlighter: pygments
latest: 2.3

version: nightly

foreman_versions:
    'nightly': nightly
    '2.4': 'releases/1.10'
    '2.3': 'releases/1.9'

version_aliases:
  '2.4': 2.4-RC

kramdown:
  auto_id: true
  input: GFM

exclude: ['vendor']
